// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWH3cTkR5KHLe_Wevi8UJU4TwkyZaLteM',
    appId: '1:676420712720:web:1736310b77ea942c670d95',
    messagingSenderId: '676420712720',
    projectId: 'movies-5889c',
    authDomain: 'movies-5889c.firebaseapp.com',
    storageBucket: 'movies-5889c.firebasestorage.app',
    measurementId: 'G-PC00L1PWPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj0So_0-KVDZMk-P99e1_QhwPpE_I8egs',
    appId: '1:676420712720:android:c407c9f852e26758670d95',
    messagingSenderId: '676420712720',
    projectId: 'movies-5889c',
    storageBucket: 'movies-5889c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApn1UOe-Z7JM29Fhb2wVQSF990vkgFW8Q',
    appId: '1:676420712720:ios:8ee5c389046c5fc8670d95',
    messagingSenderId: '676420712720',
    projectId: 'movies-5889c',
    storageBucket: 'movies-5889c.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApn1UOe-Z7JM29Fhb2wVQSF990vkgFW8Q',
    appId: '1:676420712720:ios:8ee5c389046c5fc8670d95',
    messagingSenderId: '676420712720',
    projectId: 'movies-5889c',
    storageBucket: 'movies-5889c.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWH3cTkR5KHLe_Wevi8UJU4TwkyZaLteM',
    appId: '1:676420712720:web:e1d1add575165f24670d95',
    messagingSenderId: '676420712720',
    projectId: 'movies-5889c',
    authDomain: 'movies-5889c.firebaseapp.com',
    storageBucket: 'movies-5889c.firebasestorage.app',
    measurementId: 'G-T3XMBKM59W',
  );
}
